kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-vol1-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      path: nfsshare1