apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol5
  labels:
    path: nfsshare5
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.1
    path: "/home/nfs/nfsshare5"